### ISSUE TITLE
[thunderbird] Error: Please use FINAL_TARGET_PP_FILES instead of DIST_FILES

### ISSUE THREAD

**Issue by jankeromnes** [jankeromnes/dockerfiles#3]
When I try to build `thunderbird.docker` the following error:

    $ sudo docker build - < thunderbird.docker
    [ ... a bunch of stuff happens ...]
    0:34.36 Reticulating splines...
    0:35.03 Traceback (most recent call last):
    0:35.03   File "./config.status", line 1060, in <module>
    0:35.03     config_status(**args)
    0:35.03   File "/home/user/thunderbird/mozilla/python/mozbuild/mozbuild/config_status.py", line 175, in config_status
    0:35.03     definitions = list(definitions)
    0:35.03   File "/home/user/thunderbird/mozilla/python/mozbuild/mozbuild/frontend/emitter.py", line 165, in emit
    0:35.03     for out in output:
    0:35.03   File "/home/user/thunderbird/mozilla/python/mozbuild/mozbuild/frontend/reader.py", line 1062, in read_mozbuild
    0:35.03     raise bre
    0:35.03 mozbuild.frontend.reader.BuildReaderError:
    0:35.03 ==============================
    0:35.03 ERROR PROCESSING MOZBUILD FILE
    0:35.03 ==============================
    0:35.03 
    0:35.03 The error occurred while processing the following file:
    0:35.03 
    0:35.04     /home/user/thunderbird/mail/components/devtools/extension/moz.build
    0:35.04 
    0:35.04 The error was triggered on line 11 of this file:
    0:35.04 
    0:35.04     DIST_FILES += [
    0:35.04 
    0:35.04 The underlying problem is an attempt to read a reserved UPPERCASE variable that does not exist.
    0:35.04 
    0:35.04 The variable read causing the error is:
    0:35.04 
    0:35.04     DIST_FILES
    0:35.04 
    0:35.04 Maybe you meant TESTING_FILES or BRANDING_FILES?
    0:35.04 
    0:35.04 Please use
    0:35.04 
    0:35.04     FINAL_TARGET_PP_FILES += [ 'foo' ]
    0:35.04 
    0:35.04 instead of
    0:35.04 
    0:35.04     DIST_FILES += [ 'foo' ]
    0:35.04 
    0:35.07 *** Fix above errors and then restart with\
    0:35.07                "/usr/bin/make -f client.mk build"
    0:35.07 make[1]: *** [configure] Error 1

This looks like a build issue in Thunderbird. @kewisch any ideas?

**Comment by kewisch** [comment]
This is normal build fallout, if you check comm-central on treeherder you will see similar errors. I think the bustage fix was just pushed. As Thunderbird does not have as many resources and we also depend on the Mozilla build system, it can often happen that builds are broken for a couple of days or in some situations even longer.

**Comment by jankeromnes** [comment]
Ok, thanks for the info. I wanted to re-build a clean Thunderbird image on https://janitor.technology, but for this time, and future updates re-builds, I'll just keep trying until I have a working build. I'll close this issue the next time I have a working build.

**Comment by jankeromnes** [comment]
It was indeed a transient bustage. Fixed now.
