### ISSUE TITLE
[firefox] support rr

### ISSUE THREAD

**Issue by jankeromnes** [jankeromnes/dockerfiles#6]
Record & Replay debugging can be very useful to developers, so we should install and set up [rr](https://github.com/mozilla/rr) in the Firefox base image.

**Comment by erik-harrison** [comment]
Looks like roc is providing debs - I don't have a Docker install here at work to get it up and running, but installation should be straightforward. From the webpage
```
cd /tmp
wget https://github.com/mozilla/rr/releases/download/4.2.0/rr-4.2.0-Linux-$(uname -m).deb
sudo dpkg -i rr-4.2.0-Linux-$(uname -m).deb
```

...And there shouldn't be in special setup to work with Firefox. See https://github.com/mozilla/rr/wiki/Recording-Firefox

**Comment by jankeromnes** [comment]
Very cool, thanks @erik-harrison! I just tested your instructions in my Firefox contribution on https://janitor.technology and it works great. I'll add these instructions to the Firefox dockerfile.

**Comment by jankeromnes** [comment]
a87122e73aaada14b301e8a165a452575fb16650 installs `rr 4.2.0` for all projects.
