### ISSUE TITLE
[servo] can't run graphically in noVNC

### ISSUE THREAD

**Issue by jankeromnes** [jankeromnes/dockerfiles#8]
When trying to run Servo from within [noVNC](https://github.com/kanaka/noVNC), a new window opens but then quickly disappears, and we get the following error:

    ~/servo$ ./mach run
    Xlib:  extension "XFree86-VidModeExtension" missing on display ":99.0".
    thread '<main>' panicked at 'glx::ChooseFBConfig returned no configurations.', /home/user/servo/.cargo/git/checkouts/rust-layers-[...]

![servo-fail-1](https://cloud.githubusercontent.com/assets/599268/13954180/fd8b1dba-f03f-11e5-8eaf-eac9d1dae98f.png)

A different error appears when trying to run with `webrender`:

    ~/servo$ ./mach run -w
    Xlib:  extension "XFree86-VidModeExtension" missing on display ":99.0".
    compile "/home/user/servo/resources/shaders/quad.vs.glsl"
    Failed to compile shader: 0:5(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES
    thread '<main>' panicked at '-- Shader compile failed - exiting --', /home/user/servo/.cargo/git/checkouts/webrender-[...]

![servo-fail-2](https://cloud.githubusercontent.com/assets/599268/13954310/7b2c4596-f040-11e5-81fc-46e98670a80c.png)

**Comment by jankeromnes** [comment]
FYI, here is the result of `glxinfo`:

    name of display: :99.0
    display: :99 screen: 0
    direct rendering: Yes
    server glx vendor string: SGI
    server glx version string: 1.4
    server glx extensions:
    [...]

![servo-glxinfo](https://cloud.githubusercontent.com/assets/599268/13991459/8a0adba8-f118-11e5-9271-bb1145d20fac.png)

**Comment by emilio** [comment]
Could you follow the steps suggested in https://github.com/servo/servo/issues/9932, regarding running with webrender?

Please comment there and I'll re-open it :)

**Comment by pcwalton** [comment]
It seems that noVNC does not support the X extensions that we support, nor does it support OpenGL 3.2, which we also require for now.

**Comment by jankeromnes** [comment]
`./mach run -w` now sort of works with the additional Ubuntu packages and Xvfb extensions added in 690d5d159d967c1c4c59f1ffe1062b16c67d8020.
